-- MySQL Script generated by MySQL Workbench
-- Thu Mar  9 15:42:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trophies
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trophies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trophies` DEFAULT CHARACTER SET utf8 ;
USE `trophies` ;

-- -----------------------------------------------------
-- Table `trophies`.`tp_Badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trophies`.`tp_Badge` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trophies`.`tp_Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trophies`.`tp_Player` (
  `UUID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UUID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trophies`.`PlayerBadge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trophies`.`PlayerBadge` (
  `tp_Player_UUID` VARCHAR(45) NOT NULL,
  `tp_Badge_ID` INT NOT NULL,
  `UnlockDate` DATE NOT NULL,
  `Placement` INT NULL,
  `PlayerBadgecol` VARCHAR(45) NULL,
  PRIMARY KEY (`tp_Player_UUID`, `tp_Badge_ID`),
  INDEX `fk_tp_Player_has_tp_Badge_tp_Badge1_idx` (`tp_Badge_ID` ASC) VISIBLE,
  INDEX `fk_tp_Player_has_tp_Badge_tp_Player_idx` (`tp_Player_UUID` ASC) VISIBLE,
  CONSTRAINT `fk_tp_Player_has_tp_Badge_tp_Player`
    FOREIGN KEY (`tp_Player_UUID`)
    REFERENCES `trophies`.`tp_Player` (`UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tp_Player_has_tp_Badge_tp_Badge1`
    FOREIGN KEY (`tp_Badge_ID`)
    REFERENCES `trophies`.`tp_Badge` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trophies`.`tp_Kingdom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trophies`.`tp_Kingdom` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trophies`.`KingdomBadge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trophies`.`KingdomBadge` (
  `Kingdom_id` INT NOT NULL,
  `tp_Badge_ID` INT NOT NULL,
  `UnlockDate` DATE NOT NULL,
  `Placement` INT NULL,
  PRIMARY KEY (`Kingdom_id`, `tp_Badge_ID`),
  INDEX `fk_Kingdom_has_tp_Badge_tp_Badge1_idx` (`tp_Badge_ID` ASC) VISIBLE,
  INDEX `fk_Kingdom_has_tp_Badge_Kingdom1_idx` (`Kingdom_id` ASC) VISIBLE,
  CONSTRAINT `fk_Kingdom_has_tp_Badge_Kingdom1`
    FOREIGN KEY (`Kingdom_id`)
    REFERENCES `trophies`.`tp_Kingdom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kingdom_has_tp_Badge_tp_Badge1`
    FOREIGN KEY (`tp_Badge_ID`)
    REFERENCES `trophies`.`tp_Badge` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
